Feature/a UI 004 031
GuildOpenTech/got-learn-Front pull request #21
Opened 2024-07-03 15:36 UTC by JulienDegermann

Réalisation de la Section 3 de la landing page 

Barre de progression + titre + section dynamique + CTA
- Barre de progression à 83px (selon MàJ des maquettes ?)

CTA : modification du composant CTA 
 - ajout de props (width, height, fontWeight, fontSize) => possible d’en ajouter

Update composant Section :
- style : marginX = 83px (distance scrollBar -> bord)
- prop scrollBarDist = distance par rapport à la scrollBar => valeur placée en paddingX
- prop marginTop / marginBottom : marges verticales de la section (espaces entre 2 sections)
- prop titleCenter (bool) : centrer le titre de la section (section « rejoignez le monde professionnel »)

Espace dynamique (projets) :
- fontSize en PX (si en pt, texte de base trop long et déborde + sur maquette exprimés en px)
- positionnement par rapport à la scrollbar (possible de centrer, peut être plus adapté pour le mobiles)
- préparation au responsive : affichage d'un nombre différents de projets selon la taille d'écran
- largeur d'un projet non-fixe (maxWidth: 372px)

fichier style.css
- suppression du styles header, footer, section (css-in-js dans les composants)
- over-ride style slick : d-none sur le prev arrow
- mise à jour des couleurs (couleur défaut = blanc)

+ Fix position section 2 image : right: -83px

Tests ok

2024-07-03 16:26 UTC, qjacquet requested changes
- [x] Corriger problème de taille de font globale
- [ ] Alléger le fichier Layout.tsx en déplaçant du code dans d'autres fichiers (pour plus de lisibilité)

2024-07-03 16:26 UTC, qjacquet commented on src/index.css
> +  font-size: 16px;
ça casse le rendu de la police de certains composants (comme TopSection.tsx)
Est-ce vraiment nécessaire de le mettre la ? je vois pas la mention des 16px dans la spec, ça vient du figma ?

2024-07-03 16:26 UTC, qjacquet commented on src/index.css
> +} */
on peut supprimer si pas utilisé

2024-07-03 16:26 UTC, qjacquet commented on src/views/Layout.tsx
> +
a déplacer dans un autre fichier ? src/data/projects.ts ?

2024-07-03 16:26 UTC, qjacquet commented on src/views/Layout.tsx
> +  };
a deplacer dans un autre fichier ? src/core/ui/config/slider.ts ?

2024-07-03 16:29 UTC, qjacquet commented
Autre point : j'ai un peu de mal a comprendre la taille des h2 et du contenu, ça me semble beaucoup trop gros, et surtout j'avais pas du tout les mêmes tailles sur la TopSection.

2024-07-03 16:29 UTC, JulienDegermann commented on src/views/Layout.tsx
> +
les données seront récupérées depuis le backend ? à remplacer par une requête ?

2024-07-03 16:30 UTC, JulienDegermann commented on src/index.css
> +} */
un oubli de ma part en effet

2024-07-03 16:33 UTC, JulienDegermann commented on src/index.css
> +  font-size: 16px;
j'ai dû mettre cette valeur par réflexe -> à retirer

2024-07-03 16:58 UTC, qjacquet commented on src/views/Layout.tsx
> +
Pour le moment non, on a pas d'API.
Quand on aura l'API on pourra faire une couche d'accès a l'API + les interfaces + les services/requete aux endpoint dans le Front. 

Mais vaut mieux mettre ce morceau de code a part dans un fichier quand même ça permettra de rendre le Layout.tsx un peu plus lisible.

2024-07-03 16:58 UTC, qjacquet commented on src/index.css
> +} */
c'est pas grave mais autant en profiter pour l'enlever ^^

2024-07-03 17:05 UTC, JulienDegermann commented on src/views/Layout.tsx
> +  };
j'ai un petit soucis d'utilisation de mon composant ArrowNext, il est bien importé mais dans mes settings il ne passe plus, si je commente le passage tout s'affiche correctement

2024-07-03 17:10 UTC, JulienDegermann commented
pour les titres : 
 => un Titre "Projets en cours", Police Cabin Semi bold 60 pt, interlettrage 62, blanc, à 28 px de la Barre de défilement
 
 je pense que le probleme vient de l'unité 'pt' sur la maquette c'est en px je pense
 j'ai changé pour le texte des projets, mais j'ai laissé pour les titres, je peux passer en px
 
 
 
 images : pt vs px
 
![Uploading Capture d’écran 2024-07-03 à 19.09.47.png…]()

2024-07-03 18:47 UTC, qjacquet commented
> je pense que le probleme vient de l'unité 'pt' sur la maquette c'est en px je pense

Je pense en effet que c'est en PX, c'est ce que j'avais mis dans la TopSection car ça rendait trop grand.
Je pense que tu peux changer pour les titres aussi

2024-07-03 19:25 UTC, JulienDegermann commented
j'ai mis à jour et rebase sur develop, j'ai créé un composant pour le carousel, impossible d'importer directement le svg dans le fichier de setting, j'ai dû l'ajouter directement dans le TSX

2024-07-04 11:02 UTC, qjacquet requested changes

2024-07-04 11:02 UTC, qjacquet commented on src/index.css
> +  color: var(--WHITE);
Cela casse l'affichage dans TopSection par exemple.

Il faut mettre ça soit dans html soit dans body, car l'astérisque veut dire "toutes les classes", et du coup on est obligé de le redéfinir "color" a chaque fois et ça casse l'héritage css, c'est pas pratique...

2024-07-04 11:06 UTC, qjacquet commented
> j'ai mis à jour et rebase sur develop, j'ai créé un composant pour le carousel, impossible d'importer directement le svg dans le fichier de setting, j'ai dû l'ajouter directement dans le TSX

tant pis, tant que ça fonctionne ^^

2024-07-04 21:50 UTC, qjacquet approved these changes

2024-07-04 22:46 UTC, merged